project:
  type: website
  output-dir: docs

website:
  title: "Andrew Laitha"
  site-url: "https://chlaitha.github.io/website/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: research.qmd
        text: Research
      - href: publication.qmd
        text: Publication


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



