project:
  type: website
  output-dir: docs

website:
  title: "Andrew Laitha"
  site-url: "https://chlaitha.github.io/website/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/. #automatically picks the index.gmd file in the posts folder
        text: Blog


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



